language: node_js
node_js:
- '0.11'
- '0.10'
notifications:
  email: false
addons:
  code_climate:
    repo_token:
      secure: "la7PyRNeeXUKkCre0nZdJp/Qbecbk8BsCtQ0gjm1ipZ/w76KpnV46ktF3W42PRbjRIp46ex4nQJ4KS6E1gYoA+WNnooWO3L64qoQ++RSrCu2HogFZyI913bqjcP1TsPTynosXOkae8IKnqxWjnIL9Lb6VNNUN9rwnEO4TgvRIxM="
after_script:
  - cat coverage/lcov.info | ./node_modules/.bin/codeclimate
deploy:
  provider: npm
  email: norm.maclennan@gmail.com
  on:
    tags: true
    all_branches: true
  api_key:
    secure: LZs1I7NxFvtgbmCdFXCyJxR8v2BiM+URR5ffXtteq38wdghFZUPU7dLNgDaC8DqKV3lbpuvd5j1XbskUEkAIE/XyHYiVSueG4EvyPFK4jfbYNEG8wHkWqlMGfF0SzIOVRBO2LKZYalXQHgQdUwC3GcvcNoP4aMx6ViAVJlzTovY=
